tests: Ensure vk_enum_string_helper.h is C compatible
KhronosGroup/Vulkan-Utility-Libraries pull request #68
Opened 2023-08-21 20:42 UTC by juan-lunarg

Added ifdef checks for backcompat

Intended to properly address these issue(s):
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3233
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1211

2023-08-21 21:09 UTC, juan-lunarg commented
Note. vk_enum_string_helper.h is also very confusing since it's shipped as part of the SDK like it's part of vulkan headers.

Which breaks the convention that .h files should be C compatible. And has caused confusion for numerous developers.

We didn't fix this in the past due to it living in VVL but now there is no reason AFAIK to not fix it.

2023-08-22 00:42 UTC, spencer-lunarg approved these changes
Look good to me, agree no reason these still need to be C++ now that it's own util, we (VVL repo) didn't feel we needed to "sometimes" be C compatible for what is a C++ library

2023-08-22 00:54 UTC, charles-lunarg requested changes
Forgot to hit submit...

2023-08-22 01:38 UTC, spencer-lunarg commented on scripts/generators/enum_string_helper_generator.py
> +
ya, thinking more, I agree now, would be strange to not just have it all work in C

2023-08-22 18:04 UTC, juan-lunarg commented on scripts/generators/enum_string_helper_generator.py
> +
Gotcha. Will fix.

2023-08-22 20:42 UTC, charles-lunarg approved these changes
Looks good!

2023-08-22 20:46 UTC, juan-lunarg commented on include/vulkan/vk_enum_string_helper.h
> +    if (input_value == VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT) return "VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT";
string_VkPipelineStageFlagBits2 is now C compatible 👍🏾

2023-08-22 21:13 UTC, merged